/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.SystemControl;
import java.util.HashMap;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author guilh
 */
public class UsarDB extends JFrame {

    private JFrame telaInicial;
    private String database;
    private SystemControl systemControl = new SystemControl();

    /**
     * Creates new form UsarDB
     */
    public UsarDB() {
        initComponents();
    }

    public void setCriarDb(CriarDB criarDb) {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taComandos = new javax.swing.JTextArea();
        btExecutar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbTituloBanco = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnCriarBd = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnXml = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        taComandos.setColumns(20);
        taComandos.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        taComandos.setRows(5);
        jScrollPane1.setViewportView(taComandos);

        btExecutar.setText("Executar");
        btExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExecutarActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        lbTituloBanco.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jMenu1.setText("Banco de dados");

        mnCriarBd.setText("Criar banco de dados");
        mnCriarBd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCriarBdActionPerformed(evt);
            }
        });
        jMenu1.add(mnCriarBd);
        jMenu1.add(jSeparator1);

        jMenuItem2.setBackground(new java.awt.Color(110, 110, 110));
        jMenuItem2.setForeground(new java.awt.Color(180, 180, 180));
        jMenuItem2.setText("Usar banco de dados");
        jMenuItem2.setEnabled(false);
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator2);

        mnXml.setText("Inserir dados via XML");
        mnXml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnXmlActionPerformed(evt);
            }
        });
        jMenu1.add(mnXml);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuda");

        mnSair.setText("Sair");
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });
        jMenu2.add(mnSair);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btExecutar)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTituloBanco)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(lbTituloBanco)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btExecutar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExecutarActionPerformed
        // TODO add your handling code here:
        String retorno = systemControl.recebeComando(taComandos.getText(), database);
        if (!retorno.equals("select_command")) {
            JOptionPane.showMessageDialog(rootPane, retorno);
        } else {
            HashMap<String, List<String>> retornoSelect = systemControl.getRetornoSelect();
            System.out.println(retornoSelect.toString());
        }
    }//GEN-LAST:event_btExecutarActionPerformed

    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed
        // TODO add your handling code here:        
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja mesmo sair do sistema?");
        if (resposta == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_mnSairActionPerformed

    private void mnCriarBdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCriarBdActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        telaInicial.setVisible(true);
    }//GEN-LAST:event_mnCriarBdActionPerformed

    private void mnXmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnXmlActionPerformed
        // TODO add your handling code here:
        String rota = JOptionPane.showInputDialog("Insira a rota (desde C:) do arquivo XML. \nSugestão: vá pelo Explorer até o arquivo, clique no caminho, Ctrl+C, e após colar aqui adicione o nome do arquivo + .xml.");
        rota = rota.replace("\\\\", "/");
        systemControl.setDatabase(database);
        boolean xmlValido = systemControl.validaXml(rota);
        if (xmlValido) {
            systemControl.inserePorXml(rota);
        }
    }//GEN-LAST:event_mnXmlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsarDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsarDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsarDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsarDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsarDB().setVisible(true);
            }
        });
    }

    public void setTelaInicial(JFrame telaInicial) {
        this.telaInicial = telaInicial;
    }

    public void setLbTituloBanco(String lbTituloBanco) {
        this.lbTituloBanco.setText(lbTituloBanco);
    }

    public String getDatabase() {
        return database;
    }

    public void setDatabase(String database) {
        this.database = database;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExecutar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbTituloBanco;
    private javax.swing.JMenuItem mnCriarBd;
    private javax.swing.JMenuItem mnSair;
    private javax.swing.JMenuItem mnXml;
    private javax.swing.JTextArea taComandos;
    // End of variables declaration//GEN-END:variables
}
